global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: '5s'
    target_groups:
      - targets: ['localhost:9090']

  - job_name: 'container-exporter'
    scrape_interval: '5s'
    target_groups:
      - targets: ['172.17.0.1:9104']

